#cloud-config

packages:
  - pgbouncer
  - postgresql-client

runcmd:
  - |
    cat > /etc/pgbouncer/pgbouncer.ini <<PGBEOF
    [databases]
    postgres = host=10.50.1.10 port=5432 dbname=postgres
    * = host=10.50.1.10 port=5432
    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    pool_mode = transaction
    default_pool_size = 200
    max_client_conn = 2000
    ignore_startup_parameters = extra_float_digits
    server_tls_sslmode = prefer
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    admin_users = pgbouncer
    PGBEOF
  - |
    cat > /etc/pgbouncer/userlist.txt <<USEREOF
    "pgbouncer" "StrongPass123"
    USEREOF
  - chown pgbouncer:pgbouncer /etc/pgbouncer/userlist.txt
  - chmod 640 /etc/pgbouncer/userlist.txt
  - systemctl enable pgbouncer
  - systemctl restart pgbouncer

